# Generated by Django 3.0.3 on 2020-04-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTypeModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='AdminLogi6nModel',
            new_name='AdminLoginModel',
        ),
    ]
