# Generated by Django 3.0.3 on 2020-04-15 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0002_auto_20200416_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('type_no', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.CityModel')),
            ],
        ),
    ]
